# SPDX-License-Identifier: GPL-2.0
PACKAGE_NAME="pxw3pe"
PACKAGE_VERSION="1.0"

MAKE[0]="make KDIR=${kernel_source_dir}"
CLEAN="make KDIR=${kernel_source_dir} clean"

BUILT_MODULE_NAME[0]="pxw3pe"
DEST_MODULE_LOCATION[0]="/updates/dkms"

AUTO_INSTALL="yes"
